auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: JeremyGuan.com
url: http://jeremyguan.com
feed: /atom.xml
author_info: <a href="http://jeremyguan.com/">JeremyGuan</a>