markdown: rdiscount
permalink: pretty
paginate: 5

title: Jeremy Guan
url: http://jeremyguan.com
atom: /atom.xml
rss: /rss.xml
author: Jeremy Guan
email: jeremy.guan@gmail.com

disqus_enabled: true
disqus_name: jeremyguan

excerpt_separator: ""